name       : libltc
version    : 1.3.1
release    : 2
source     :
    - https://github.com/x42/libltc/releases/download/v1.3.1/libltc-1.3.1.tar.gz : 50e63eb3b767151bc0159a3cc5d426d03a42fd69029bc9b3b7c346555f4b709c
license    : LGPL-3.0-or-later
component  : multimedia.library
summary    : libLTC provides functionality to encode and decode LTC audio from/to SMPTE or EBU timecode, including SMPTE date support.
description: |
    libLTC provides functionality to encode and decode LTC audio from/to SMPTE or EBU timecode, including SMPTE date support. Linear (or Longitudinal) Timecode (LTC) is an encoding of SMPTE timecode data as a Manchester-Biphase encoded audio signal. The audio signal is commonly recorded on a VTR track or other storage media.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
