name       : libltc
version    : 1.3.0
release    : 1
source     :
    - https://github.com/x42/libltc/releases/download/v1.3.0/libltc-1.3.0.tar.gz : aab1de052bc61fbac6ea66d88f04e95b7d5faa1ef297b95ea6a1a548c87dee5c
license    : LGPL-3.0-or-later
component  : multimedia.library
summary    : libLTC provides functionality to encode and decode LTC audio from/to SMPTE or EBU timecode, including SMPTE date support.
description: |
    libLTC provides functionality to encode and decode LTC audio from/to SMPTE or EBU timecode, including SMPTE date support. Linear (or Longitudinal) Timecode (LTC) is an encoding of SMPTE timecode data as a Manchester-Biphase encoded audio signal. The audio signal is commonly recorded on a VTR track or other storage media.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
